implemented converyor belt controls
huskyroboticsteam/science-cli pull request #2
Opened 2024-04-23 01:06 UTC by sarahfredrickson

Added conveyor belt controls. Not sure if we still need drill cover or cup indices for the lazy susan.

2024-04-23 20:46 UTC, abhaybd requested changes
Overall looks good, I think you made a typo in the power constant, and also can you clean up the extraneous whitespace changes?

In any case, after fixing the power constant this looks fine for preliminary testing

2024-04-23 20:46 UTC, abhaybd commented on science.py
> +CONVEYOR_BELT_POWER = 0x10000
Power values should be between -1 and 1, this is like ~65k

2024-05-25 18:57 UTC, sarahfredrickson commented
Still debugging issues with the notifier for the sensor reading.

2024-08-15 01:59 UTC, abhaybd commented
Science board completely changed, code has been cannibalized and used in the circ-24 branch

2024-08-15 01:59 UTC, closed without merging